Integrate graph viz wrapper
MobileUpLLC/Module-Graph-Gradle-Plugin pull request #14
Opened 2022-11-30 09:55 UTC by Takexito

2022-11-30 10:46 UTC, aartikov requested changes

2022-11-30 10:46 UTC, aartikov commented on README.md
> +4) To detect dependency cycles run `gradlew detectGraphCycle`
detectGraphCycle -> detectGraphCycle**s**

2022-11-30 10:46 UTC, aartikov commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GenerateGraphImageTask.kt
>      }
Было бы удобно, чтоб поддерживался и png и svg. Формат можно определять по расширению в имени `outputFile`

2022-11-30 10:46 UTC, aartikov commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GraphCycleDetectTask.kt
>      var ignoreCycle: Boolean = false
Вместо ignoreCycle было бы удобнее пользоваться int-переменной maxCycleCount.

Представь, что мы подключили плагин на существующий проект. В нем уже будут циклы, но мы хотим контролировать, чтоб их не становилось больше. Тогда мы выставим maxCycleCount равным текущему количеству циклов.

2022-11-30 10:46 UTC, aartikov commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GraphCycleDetectTask.kt
> +    private val checker = GraphCycleChecker()
checker (и в переменной и в названии класса) можно переименовать в detector, а метод check в detect.

Слово check у меня ассоциируется с булевым ответом - "есть циклы / нет циклов", поэтому мне кажется, что слово detect подходит лучше.

2022-11-30 10:46 UTC, aartikov commented on src/main/kotlin/ru/mobileup/modulegraph/graph/GraphCycleChecker.kt
> +        }
я плохо знаю этот алгоритм, не могу на глаз провалидировать. Давай, напишем юнит тесты для GraphCycleChecker ?

2022-11-30 10:46 UTC, aartikov commented on src/test/kotlin/test_env/PluginTest.kt
> +    }
файлы build.gradle и settings.gradle можно не генерировать кодом, а копировать подготовленные файлы во временную папку

2022-11-30 10:46 UTC, aartikov commented on src/test/kotlin/test_env/PluginTest.kt
> +    }
В идеале в этих тестах нужно проверить что-то еще, кроме того, что не было эксепшенов.

Например, сравнить созданный svg файл с ожидаемым. Проверить, что в result.output нужное значение.
Получатся end-to-end тесты для плагина.

2022-12-01 07:23 UTC, Takexito commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GraphCycleDetectTask.kt
> +    private val checker = GraphCycleChecker()
done

2022-12-01 07:23 UTC, Takexito commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GraphCycleDetectTask.kt
>      var ignoreCycle: Boolean = false
done

2022-12-01 07:25 UTC, Takexito commented on README.md
> +4) To detect dependency cycles run `gradlew detectGraphCycle`
done

2022-12-01 07:34 UTC, Takexito commented on src/main/kotlin/ru/mobileup/modulegraph/gradle/tasks/GenerateGraphImageTask.kt
>      }
done

2022-12-01 08:03 UTC, Takexito commented on src/test/kotlin/test_env/PluginTest.kt
> +    }
done

2022-12-12 13:32 UTC, Takexito commented on src/main/kotlin/ru/mobileup/modulegraph/graph/GraphCycleChecker.kt
> +        }
done

2022-12-12 13:34 UTC, Takexito commented on src/test/kotlin/test_env/PluginTest.kt
> +    }
Да, я с тобой согласен, но сейчас этот тест используется мной для простого запуска и проверки работоспособности плагина.
Я предлагаю пока что оставить так, а в одной из следующих итераций привести их к должному виду

2022-12-13 11:26 UTC, aartikov approved these changes

2022-12-13 11:26 UTC, merged